---
driver:
  name: vagrant

platforms:
  - name: debian-9
  - name: centos-7

# See https://github.com/test-kitchen/test-kitchen/issues/1075#issuecomment-283188928
# Fixes tests via Vagrant for CentOS 7
transport:
  max_ssh_sessions: 6

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_version: <%= ENV['ANSIBLE_VERSION'] || '2.5.1' %>
  require_pip: true
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] || nil %>
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  sudo_command: sudo -E -H

verifier:
  name: inspec

suites:
  - name: default
