---
driver:
  name: vagrant

platforms:
  - name: debian-9

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_version: <%= ENV['ANSIBLE_VERSION'] || '2.4.3' %>
  require_pip: true
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] || nil %>
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  sudo_command: sudo -E -H

verifier:
  name: inspec

suites:
  - name: default
