---
driver:
  name: docker
  require_chef_omnibus: false
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_version: <%= ENV['ANSIBLE_VERSION'] || '2.4.3' %>
  require_pip: true
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] || nil %>
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  sudo_command: sudo -E -H

platforms:
  - name: debian-9
    driver_config:
      run_command: /lib/systemd/systemd
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

verifier:
  name: inspec

suites:
  - name: default
