---
language: python
python: "2.7"
sudo: required
env:
  - ANSIBLE_VERSION: 2.4.3
  - ANSIBLE_VERSION: 2.3.3

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle install

script:
  - bundle exec rubocop
  - bundle exec kitchen test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
