---
language: python
python: "2.7"
sudo: false

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle install

script:
  - bundle exec rubocop
  - bundle exec kitchen test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
