---
language: python
python: "2.7"
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
install:
  - pip install --user pipenv
  - pipenv install --two --dev
script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
