- name: Ensure sensu-agent config is setup
  template:
    src: agent.yml.j2
    dest: "{{ sensu2_agent_config_file }}"
    owner: "{{ sensu2_config_owner }}"
    group: "{{ sensu2_config_group }}"
    mode: "{{ sensu2_config_mode }}"
  notify: restart sensu-agent

- name: Cleanup example agent config
  file:
    path: /etc/sensu/agent.yml.example
    state: absent
  when: sensu2_agent_cleanup_example
