- name: Ensure sensu-backend config is setup
  template:
    src: backend.yml.j2
    dest: "{{ sensu2_backend_config_file }}"
    owner: "{{ sensu2_config_owner }}"
    group: "{{ sensu2_config_group }}"
    mode: "{{ sensu2_config_mode }}"
  notify: restart sensu-backend

- name: Cleanup example sensu-backend config
  file:
    path: /etc/sensu/backend.yml.example
    state: absent
  when: sensu2_backend_cleanup_example
