---
- name: Verify
  hosts: all
  become: true
  vars:
    inspec_download_source_dir: /usr/local/src
    inspec_bin: /opt/inspec/bin/inspec
    inspec_test_directory: "/tmp/molecule/inspec"
    inspec_downloads:
      el6:
        url: https://packages.chef.io/files/stable/inspec/3.0.25/el/6/inspec-3.0.25-1.el6.x86_64.rpm
        sha256: 2ebece63787ebb4e6d1b2f853e54e4215c895e83eed9b77c517dc6c8d69190d0
      el7:
        url: https://packages.chef.io/files/stable/inspec/3.0.25/el/7/inspec-3.0.25-1.el7.x86_64.rpm
        sha256: fbfa6de5bfcebd5f4a3129dae30589023c5451d2a4467303089ed34817e21f85
      ubuntu1404:
        url: https://packages.chef.io/files/stable/inspec/3.0.25/ubuntu/14.04/inspec_3.0.25-1_amd64.deb
        sha256: 548529417f53ae4078e65a5b4a0fa2b4265a55e323c19772628d96c2771b64c2
      ubuntu1604:
        url: https://packages.chef.io/files/stable/inspec/3.0.25/ubuntu/16.04/inspec_3.0.25-1_amd64.deb
        sha256: 548529417f53ae4078e65a5b4a0fa2b4265a55e323c19772628d96c2771b64c2
      ubuntu1804:
        url: https://packages.chef.io/files/stable/inspec/3.0.25/ubuntu/18.04/inspec_3.0.25-1_amd64.deb
        sha256: 548529417f53ae4078e65a5b4a0fa2b4265a55e323c19772628d96c2771b64c2
    inspec_package_deps:
      - lsof
      - net-tools
  tasks:
    - name: Install system dependencies for Inspec
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ inspec_package_deps }}"

    - name: Download Inspec
      get_url:
        url: "{{ inspec_downloads[inspec_version]['url'] }}"
        dest: "{{ inspec_download_source_dir }}"
        sha256sum: "{{ inspec_downloads[inspec_version]['sha256'] }}"
        mode: 0755
      register: inspec_download

    - name: Install Inspec
      yum:
        name: "{{ inspec_download.dest }}"
        state: latest
      when: ansible_pkg_mgr == 'yum'

    - name: Install Inspec
      dnf:
        name: "{{ inspec_download.dest }}"
        state: latest
      when: ansible_pkg_mgr == 'dnf'

    - name: Install Inspec
      apt:
        deb: "{{ inspec_download.dest }}"
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Create Molecule directory for test files
      file:
        path: "{{ inspec_test_directory }}"
        state: directory

    - name: Copy Inspec tests to remote
      copy:
        src: "{{ item }}"
        dest: "{{ inspec_test_directory }}/{{ item | basename }}"
      with_fileglob:
        - "{{ playbook_dir }}/tests/test_*.rb"

    - name: Register test files
      shell: "ls {{ inspec_test_directory }}/test_*.rb"
      register: test_files

    - name: Execute Inspec tests
      command: "{{ inspec_bin }} exec {{ item }} --no-color --reporter progress"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      ignore_errors: true

    - name: Display details about the Inspec results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Inspec failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
