---
- name: Verify
  hosts: all
  become: true
  vars:
    inspec_download_source_dir: /usr/local/src
    inspec_bin: /opt/inspec/bin/inspec
    inspec_test_directory: "/tmp/molecule/inspec"
    inspec_downloads:
      el6:
        url: https://packages.chef.io/files/stable/inspec/3.0.64/el/6/inspec-3.0.64-1.el6.x86_64.rpm
        sha256: 538af11f2962b615c66a1acbca72e9b81266614772fb41e26712eccfe00617a1
      el7:
        url: https://packages.chef.io/files/stable/inspec/3.0.64/el/7/inspec-3.0.64-1.el7.x86_64.rpm
        sha256: 0a0210a20ad6687acf762a5200e0af5e233ae45ee3d51311d0fb3d75c0a12855
      ubuntu1404:
        url: https://packages.chef.io/files/stable/inspec/3.0.64/ubuntu/14.04/inspec_3.0.64-1_amd64.deb
        sha256: 9d4e19eee159b06007eaedf61e53638838af91fe6e8d92ed8fee560b4b67b52b
      ubuntu1604:
        url: https://packages.chef.io/files/stable/inspec/3.0.64/ubuntu/16.04/inspec_3.0.64-1_amd64.deb
        sha256: 9d4e19eee159b06007eaedf61e53638838af91fe6e8d92ed8fee560b4b67b52b
      ubuntu1804:
        url: https://packages.chef.io/files/stable/inspec/3.0.64/ubuntu/18.04/inspec_3.0.64-1_amd64.deb
        sha256: 9d4e19eee159b06007eaedf61e53638838af91fe6e8d92ed8fee560b4b67b52b
    inspec_package_deps:
      - lsof
      - net-tools
  tasks:
    - name: Install system dependencies for Inspec
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ inspec_package_deps }}"

    - name: Download Inspec
      get_url:
        url: "{{ inspec_downloads[inspec_version]['url'] }}"
        dest: "{{ inspec_download_source_dir }}"
        sha256sum: "{{ inspec_downloads[inspec_version]['sha256'] }}"
        mode: 0755
      register: inspec_download

    - name: Install Inspec
      yum:
        name: "{{ inspec_download.dest }}"
        state: latest
      when: ansible_pkg_mgr == 'yum'

    - name: Install Inspec
      dnf:
        name: "{{ inspec_download.dest }}"
        state: latest
      when: ansible_pkg_mgr == 'dnf'

    - name: Install Inspec
      apt:
        deb: "{{ inspec_download.dest }}"
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Create Molecule directory for test files
      file:
        path: "{{ inspec_test_directory }}"
        state: directory

    - name: Copy Inspec tests to remote
      copy:
        src: "{{ item }}"
        dest: "{{ inspec_test_directory }}/{{ item | basename }}"
      with_fileglob:
        - "{{ playbook_dir }}/tests/test_*.rb"

    - name: Register test files
      shell: "ls {{ inspec_test_directory }}/test_*.rb"
      register: test_files

    - name: Execute Inspec tests
      command: "{{ inspec_bin }} exec {{ item }} --no-color --reporter progress"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      ignore_errors: true

    - name: Display details about the Inspec results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Inspec failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
