---
scenario:
  name: amazonlinux
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: amazonlinux-1
    image: dokken/amazonlinux
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
  - name: amazonlinux-2
    image: dokken/amazonlinux-2
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      poll_interval: 3
      forks: 100
    connection:
      pipelining: true
  playbooks:
    prepare: ../shared/prepare.yml
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/playbook.yml
    verify: ../shared/verify.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      amazonlinux-1:
        sensu2_repos_overrides:
          yum:
            rpm: https://packagecloud.io/sensu/nightly/el/6/x86_64
            rpm-src: https://packagecloud.io/sensu/nightly/el/6/SRPMS
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.2.16/el/6/inspec-2.2.16-1.el6.x86_64.rpm
        inspec_download_sha256sum: 616af0700b3c80f545d143dfe24c987039a8d715cbb615aac5ad94b0e0b34323
      amazonlinux-2:
        sensu2_repos_overrides:
          yum:
            rpm: https://packagecloud.io/sensu/nightly/el/7/x86_64
            rpm-src: https://packagecloud.io/sensu/nightly/el/7/SRPMS
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.2.16/el/7/inspec-2.2.16-1.el7.x86_64.rpm
        inspec_download_sha256sum: 2fdf2000630c38828c3172d471a61ecc4b8ff58ce9bee9a5543a99434be30e83
verifier:
  name: inspec
  directory: ../shared/tests/
  lint:
    name: rubocop
