- name: Ensure sensu-backend service state
  service:
    name: sensu-backend
    enabled: "{{ sensu2_backend_enabled }}"
    state: "{{ sensu2_backend_state }}"
  register: sensu2_backend_service_state

- debug:
    var: sensu2_backend_service_state

- name: Wait for sensu-backend to be online
  wait_for:
    port: 8081
    delay: 30
  when: sensu2_backend_service_state | changed
